In [4]:
import pandas as pd
df_books = pd.read_csv('https://github.com/cesarmayta/datasets/raw/refs/heads/main/libros.csv')
df_books.shape

(550, 7)

### FILTRAR POR GENERO 'FICTION' Y RATING > 4
### MOSTRAR SOLO NAME,AUTHOR, USER RATING, PRICE

In [7]:
df_books[(df_books['Genre']=='Fiction') & (df_books['User Rating'] > 4)][['Name','Author','User Rating','Price']]

,Name,Author,User Rating,Price
1,11/22/63: A Novel,Stephen King,4.6,22
3,1984 (Signet Classics),George Orwell,4.7,6
5,A Dance with Dragons (A Song of Ice and Fire),George R. R. Martin,4.4,11
6,A Game of Thrones / A Clash of Kings / A Storm...,George R. R. Martin,4.7,30
7,A Gentleman in Moscow: A Novel,Amor Towles,4.7,15
...,...,...,...,...
541,Wonder,R. J. Palacio,4.8,9
542,Wonder,R. J. Palacio,4.8,9
543,Wonder,R. J. Palacio,4.8,9
544,Wonder,R. J. Palacio,4.8,9
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,8

### AGRUPA POR AUTHOR , MUESTRA PRECIO PROMEDIO, TOTAL DE LIBROS

In [13]:
df_books.groupby('Author').agg(
    precio_promedio=('Price','mean'),
    total_libros=('Name','count')
).reset_index()

                         Author  precio_promedio  total_libros
0              Abraham Verghese        11.000000             2
1                Adam Gasiewski         6.000000             1
2                 Adam Mansbach         9.000000             1
3                     Adir Levy        13.000000             1
4    Admiral William H. McRaven        11.000000             1
..                          ...              ...           ...
243             Walter Isaacson        20.333333             3
244               William Davis         6.000000             2
245            William P. Young         8.000000             2
246            Wizards RPG Team        27.000000             3
247                Zhi Gang Sha        11.500000             2

[248 rows x 3 columns]